<a href="https://colab.research.google.com/github/HackElite-FYP/Legal-Research-Platform-Core/blob/feature%2Fentity-mapping/cases%2C%20acts%20reference.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%pip install neo4j

Collecting neo4j
  Downloading neo4j-5.28.1-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: pytz in /usr/local/lib/python3.11/dist-packages (from neo4j) (2025.2)
Downloading neo4j-5.28.1-py3-none-any.whl (312 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 312.3/312.3 kB 4.7 MB/s eta 0:00:00
Installing collected packages: neo4j
Successfully installed neo4j-5.28.1

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# 📦 Required imports
import json
import re
import pandas as pd
from neo4j import GraphDatabase
from IPython.display import display

In [5]:
filename = "cases_2024_v2.json"
!wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1meeq_pyxndS9W7mmavcX_srExlpYi5Hw' -O {filename}

--2025-07-22 15:16:12--  https://docs.google.com/uc?export=download&id=1meeq_pyxndS9W7mmavcX_srExlpYi5Hw
Resolving docs.google.com (docs.google.com)... 74.125.139.113, 74.125.139.100, 74.125.139.138, ...
Connecting to docs.google.com (docs.google.com)|74.125.139.113|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1meeq_pyxndS9W7mmavcX_srExlpYi5Hw&export=download [following]
--2025-07-22 15:16:12--  https://drive.usercontent.google.com/download?id=1meeq_pyxndS9W7mmavcX_srExlpYi5Hw&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.251.107.132, 2607:f8b0:400c:c32::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.251.107.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 30688975 (29M) [application/octet-stream]
Saving to: ‘cases_2024_v2.json’

cases_2024_v2.json  100%[===================>]  29.27M   152MB/s    in 0.2s

2025-07-22 15:16:27 (152 MB/s) - ‘cases_2024_v2.json’ saved [30688975/30688975]

In [6]:
# 📁 Configuration and Data Loading

# CHANGE THIS LINE to point to your file path
file_path = r"cases_2024_v2.json"

try:
    with open(file_path, 'r', encoding='utf-8') as file:
        case_data = json.load(file)
    print(f"✅ Successfully loaded {len(case_data)} records from case data.")
except FileNotFoundError:
    print(f"❌ Error: The file was not found at {file_path}")
    print("Please ensure the file path is correct and that your Google Drive is mounted if you're using Colab.")
    case_data = []

✅ Successfully loaded 530 records from case data.

In [7]:
# 📌 Define function to extract and format acts in "Act Name, No. X of YYYY" format
def extract_acts(text):
    pattern = r'([A-Z][a-zA-Z\s()]*?Act(?:,?|\s+))\s*No\.?\s*(\d+)\s*(?:of)?\s*(\d{4})'
    matches = re.findall(pattern, text)
    return [f"{name.strip()}, No. {num} of {year}" for name, num, year in matches]

# 🧠 Process each case's content
raw_case_act_map = []
if case_data:
    print("Processing case data to extract raw act references...")
    for case in case_data:
        case_id = case.get("id", "Unknown")
        file_name = case.get("filename", "")

        content = case.get("translated", "").replace('\n', ' ')

        # 🔍 Use the extract_acts function instead of inline regex
        acts_found = extract_acts(content)
        filtered_acts = []
        for act in acts_found:
            if len(act.split()) < 10:
                filtered_acts.append(act)

        if filtered_acts:
            raw_case_act_map.append({
                "case_id": case_id,
                "filename":file_name,
                "raw_acts": sorted(list(set(filtered_acts)))
            })
        else:
            print(f"⚠️ No act references found in case {case_id}")
            raw_case_act_map.append({
                "case_id": case_id,
                "filename":file_name,
                "raw_acts": []
            })

    print(f"✅ Extraction complete. Found act references in {len(raw_case_act_map)} cases.")
else:
    print("⚠️ No case data to process.")

# 📊 Preview the result
raw_df = pd.DataFrame(raw_case_act_map)
print("\n📋 Preview of Extracted and Formatted Act References:")
display(raw_df)

Processing case data to extract raw act references...
⚠️ No act references found in case 8fb1373c-2b19-4df4-bbcc-40b0720dc9b3
⚠️ No act references found in case f377d509-ea0d-4a2f-9e7a-4d2a14515d19
⚠️ No act references found in case 3f222e28-d9a0-452e-aa98-498d5656613e
⚠️ No act references found in case eaaf5922-459d-46c6-8a6d-7d943cf59802
⚠️ No act references found in case 8a23d9c9-b5b6-4c47-87ef-ab9d38ab5272
⚠️ No act references found in case 70e90de1-f93f-48d9-840a-6a2b1b067278
⚠️ No act references found in case 8a1844b8-851e-4ad5-ae21-ce790eb9c199
⚠️ No act references found in case 1879977a-a086-41c6-a1e3-5fc4fcf05ab1
⚠️ No act references found in case 1fd3711c-cee9-4d59-9023-a32cd006f8d1
⚠️ No act references found in case a8214375-4576-411e-9849-fbb225ce6f16
⚠️ No act references found in case 0b62012f-a1fb-435b-80d5-2a867b52ad09
⚠️ No act references found in case 2acb30b0-4625-44c1-8e66-4224f774d4bf
⚠️ No act references found in case 766f067d-f06a-4953-bbe3-444a2c498bd6
⚠️ No act references found in case e18d4705-26a5-4c70-9216-5542b8693941
⚠️ No act references found in case 87059a23-5b75-4105-a616-cf5ecf1fd0df
⚠️ No act references found in case ac043c15-2add-4c59-836b-65a5d08869c9
⚠️ No act references found in case 5c5d435b-9a04-4982-9315-d86e724ee2ff
⚠️ No act references found in case cf7603c3-eaac-4afc-ba52-108d869271fd
⚠️ No act references found in case e1c74410-95b5-4673-8e18-3c1e07808fea
⚠️ No act references found in case b8e84465-1397-4497-ba67-52f06e90ca24
⚠️ No act references found in case 11a0f7fd-e554-43cf-874d-58d3ccf2ee44
⚠️ No act references found in case 478912e5-e6ae-4331-913e-67807f3a190d
⚠️ No act references found in case 9046e351-ece0-4ec9-befb-b510ad75ba35
⚠️ No act references found in case 8ed9ea40-b285-43f5-a3b3-85342677cf5e
⚠️ No act references found in case ca849a2a-fb07-41dc-96ee-6da806509357
⚠️ No act references found in case 49cc1460-8ed5-434e-b19e-85a598e5c0dd
⚠️ No act references found in case e91375a2-16eb-40d9-89ed-c00a58f183c9
⚠️ No act references found in case 4ea5ae9c-ecd2-42cf-8001-6e843b357b65
⚠️ No act references found in case 7f992d67-e4c4-4e12-8cd3-2b8c19fae301
⚠️ No act references found in case a2db6889-5eef-457b-a6d5-ca043fd23207
⚠️ No act references found in case 9c422859-f88d-4ac1-8cb5-862c47f44517
⚠️ No act references found in case 82763803-d062-4b9a-9ab0-6cdfbfb16082
⚠️ No act references found in case 64d3c8d1-e0b6-45a7-92fc-76d9c5c11445
⚠️ No act references found in case a111fc60-fcf9-4e9d-b2d5-dfe223d04832
⚠️ No act references found in case 9db42518-a10a-4d5b-8ba3-fd2d7110a46d
⚠️ No act references found in case 8615cb05-fa9e-4e8f-906d-3dafa3419e7e
⚠️ No act references found in case 4a034773-c685-408f-8c3e-d4cb40c5049c
⚠️ No act references found in case 78910e92-0665-4c1a-bf51-6d49d87457c3
⚠️ No act references found in case e71ab068-62d0-4192-ac11-958c6b2dddd7
⚠️ No act references found in case 237700f2-6252-40e4-9d16-e1e05ebfbfe5
⚠️ No act references found in case 997893ef-099d-40a5-903b-1d5ca3a77d89
⚠️ No act references found in case b43a5cae-2a7b-43c5-a658-921752cb2f24
⚠️ No act references found in case 6b397e17-67f0-4a49-8ca9-64903f5745db
⚠️ No act references found in case be41a342-ff76-4b43-b574-c016ceb99e5a
⚠️ No act references found in case dc6ff29a-02b1-4d34-8567-498ee09e229b
⚠️ No act references found in case e32dd0fd-caa5-4e1d-a4ac-7a99af25bd39
⚠️ No act references found in case 8354a3ab-e548-477e-8ff6-efc40917a171
⚠️ No act references found in case e1a554e3-5ef3-49a6-889a-cf1abd13fb40
⚠️ No act references found in case bc8308c7-7abe-4250-a07c-2dd913c324b2
⚠️ No act references found in case 1225feb1-0f30-46ee-bd1c-5180eeb5c601
⚠️ No act references found in case aad05a37-c875-47bc-b999-9c7d7f78a36d
⚠️ No act references found in case 1e191d25-804a-4089-9fe7-a3db5f355b52
⚠️ No act references found in case 08f48d45-c717-4ac5-8626-3372918d07aa
⚠️ No act references found in case c24336e5-676c-44db-94b8-ca4cc418f7fa
⚠️ No act references found in case c83188b6-db26-4881-be1f-7001df170751
⚠️ No act references found in case 230029f2-0f9c-436c-9b85-7a3093788ab7
⚠️ No act references found in case feef7510-85d1-4008-90cd-d1bf610c3f1d
⚠️ No act references found in case 4f732cca-c1a1-444b-a9cf-4df2d867fb65
⚠️ No act references found in case 28ccd4da-82a9-44d5-9097-3f2ccc1b4d17
⚠️ No act references found in case 7b8e6f55-246e-4329-97bd-4834de5d6228
⚠️ No act references found in case 8becedd8-3b50-4977-b7cb-733af96669ae
⚠️ No act references found in case fd50c234-c49e-440d-9748-3962e204acdf
⚠️ No act references found in case a096ca11-1976-4606-afd8-6fda8566560d
⚠️ No act references found in case b13bfa02-76b8-437c-b587-61b0c56aa04a
⚠️ No act references found in case 4d06398d-977a-4129-8661-ff358f3c5487
⚠️ No act references found in case 12949064-b074-471c-8a17-d5d6bd6597f8
⚠️ No act references found in case c4ef11b6-f7a6-4c95-ad35-4ea23de886bf
⚠️ No act references found in case ba34336d-c194-4c8d-a873-c07d6de7ed01
⚠️ No act references found in case 4286ec96-bcdc-4f8f-ab05-26370423dbc0
⚠️ No act references found in case 1c188f6d-3832-4641-8f4a-a19c747cc0b5
⚠️ No act references found in case 7b6aa5f6-c52c-4eec-8b58-eb95316b4072
⚠️ No act references found in case baf6be9b-ad31-4da2-976c-f756ec350021
⚠️ No act references found in case c01c70c7-6bd3-4baf-9b14-4433f09c25c4
⚠️ No act references found in case d9568be1-3aa6-4596-858a-1e9d9b18ae4c
⚠️ No act references found in case a634ab9a-1a3b-4ad1-bfda-e7ff4bb5f101
⚠️ No act references found in case 239785d6-2cdd-46bc-a88f-80354bf5bb30
⚠️ No act references found in case 01678304-fafe-410c-93c4-9eb6b147acaf
⚠️ No act references found in case 41d80e88-2173-4d7d-abd7-329807e73477
⚠️ No act references found in case 4ada41bf-3e2a-4107-aa78-0486503fb289
⚠️ No act references found in case d179cfda-c0e1-4ad4-93d1-6a9af95a3722
⚠️ No act references found in case 082359b1-0049-4a61-a436-51f5583832ac
⚠️ No act references found in case a7bbb81f-e817-4ae7-a265-3a3957547cb1
⚠️ No act references found in case 0728263e-0343-4101-908c-9aaaec356ea4
⚠️ No act references found in case 71a4f042-ec3f-4056-988e-9a28d4d3447e
⚠️ No act references found in case 451a21c1-c07b-4b76-aba2-084b635eef66
⚠️ No act references found in case bab543fa-d1ef-4718-bbf4-a28d6077d5ab
⚠️ No act references found in case fb842387-f41a-49bd-a31d-c287210ad0b2
⚠️ No act references found in case c2130377-fb03-41d5-85f1-980b613c65d9
⚠️ No act references found in case 471b5e7b-9283-4527-b7ca-be576c990cca
⚠️ No act references found in case aed75516-fba6-4af7-94fc-838145f9c8df
⚠️ No act references found in case 24b89c2c-6ad8-477d-ae6c-ca05199bef91
⚠️ No act references found in case 064f53c2-43b8-43bf-af14-4677be56b484
⚠️ No act references found in case af2ad53c-541a-4f0e-a6a9-05acde022dd7
⚠️ No act references found in case 935f5861-89b2-45ad-ba11-a850b2a6a212
⚠️ No act references found in case 0b03db14-7e1c-41d1-b75f-bc930a9702c7
⚠️ No act references found in case ef2f8041-7870-471f-ae54-98916377b35e
⚠️ No act references found in case 670aacd2-2076-4536-b196-8cb77ca5822d
⚠️ No act references found in case 34383139-c8e3-48a4-b261-fb6ce0790393
⚠️ No act references found in case 95404603-658d-4e41-9858-2c51f849f01a
⚠️ No act references found in case 75ce9b97-3987-40a7-89ec-8047db3fdea7
⚠️ No act references found in case 295ab45e-7da3-4336-8698-ca0c4ec75e4a
⚠️ No act references found in case c305cef2-a189-4d17-82f1-dc1577b3ea6a
⚠️ No act references found in case ae11b754-4c97-43c5-8ed1-03f3c3382dbc
⚠️ No act references found in case d37f1d4e-83ff-49b8-a270-281aad401807
⚠️ No act references found in case 74463333-390d-4f93-a514-b8874262efd0
⚠️ No act references found in case 19ffe04a-fc8a-41aa-8ec4-f0ca0266a8f9
⚠️ No act references found in case 5437caf3-58c8-4f10-b286-11e19c2f697a
⚠️ No act references found in case 9a0c6c03-945f-48ba-9cde-0bfd81ff4718
⚠️ No act references found in case 1b895da5-766d-4549-9f2c-111b7dd050ee
⚠️ No act references found in case f4ee2a56-59b2-4601-91fb-af5cbf2afd30
⚠️ No act references found in case 3cbc61c2-6c60-45c1-aa83-6d4911f1a80b
⚠️ No act references found in case 80dccf2c-b709-45b4-bdc4-b38d1d9bca28
⚠️ No act references found in case 07ce6884-2cc9-4001-8c00-dc6c3c22f548
⚠️ No act references found in case a12afdc7-dba0-4325-8ff3-dc5cc785c22a
⚠️ No act references found in case 4b19cc5d-b4a1-44a1-8d2a-22925600e873
⚠️ No act references found in case 80f4e883-a2b3-4391-9812-5bb2ade2ae44
⚠️ No act references found in case 4f8f25df-dd87-4a26-9f47-703367d31eda
⚠️ No act references found in case d88f805b-5eea-4280-a8cc-6fdfc2181807
⚠️ No act references found in case f23752eb-37cd-47dd-8986-b22b19836ebe
⚠️ No act references found in case f78ad6c0-25a6-4313-9ef4-acdcf13f9984
⚠️ No act references found in case e3e4b968-7b4a-45da-8c31-72f04b2876a5
⚠️ No act references found in case 3820f8f0-fb08-4b00-8083-dcdf15feb13e
⚠️ No act references found in case 05d738bb-6b65-4ab6-87dc-9430ac1db158
⚠️ No act references found in case 2b8380b7-f175-4a71-91b1-9fb9d7dc4758
⚠️ No act references found in case d8c02994-c781-41f7-b5e7-9bc6c6916371
⚠️ No act references found in case a7eb4b83-8a0a-4f26-bce9-6f43bcd67469
⚠️ No act references found in case e18615e5-3c60-45fd-ad38-430b739a3efb
⚠️ No act references found in case 262aedba-2fcc-49a5-b535-d325ae576489
⚠️ No act references found in case 4a1ace84-ef95-4a42-9794-913fc2eef79b
⚠️ No act references found in case 87666ed1-8f7c-4e5d-9f52-b7c1307188a0
⚠️ No act references found in case 6b5ad828-993f-4558-9413-7f618b777058
⚠️ No act references found in case ec5b0f83-bcca-4d7e-a788-b1e79ce87768
⚠️ No act references found in case cf6ea2c0-c0f4-4fe6-9f84-c554e86d410e
⚠️ No act references found in case 45badd58-4c55-4219-9f61-e7e6b7ba0192
⚠️ No act references found in case ad3f408d-4361-465a-a0bd-00192acac37a
⚠️ No act references found in case 072d36cd-d3b8-473d-8f1c-008924ee8cbf
⚠️ No act references found in case dbd82ae2-7efd-48f4-a31c-5658669c0c41
⚠️ No act references found in case 143f0a1a-686b-4cba-88d9-1865cec05e5f
⚠️ No act references found in case 0e292e21-9b0b-4b5e-8cd1-9f10400a1f32
⚠️ No act references found in case 2c79bbf9-aedb-4d42-9dbc-c155c6c58941
⚠️ No act references found in case d2344814-e35a-4569-b34b-d223802ba2d0
⚠️ No act references found in case 5322bcba-f846-4674-bcdd-b429f672a544
⚠️ No act references found in case 12371d9b-4dac-4c40-9487-4c1f759ad9f8
⚠️ No act references found in case b0e99071-e96f-4849-9b34-b5be6751de86
⚠️ No act references found in case 56753735-24a6-4c13-bbcc-b8a217cf3a15
⚠️ No act references found in case 9312caf3-c75f-476d-994e-6ae9ca9b5617
⚠️ No act references found in case b35d1893-71f1-484b-bbf0-2a0ce282e928
⚠️ No act references found in case 3bb0f104-b93d-4093-a7d2-97f5139b60ab
⚠️ No act references found in case f61db562-24bf-42a2-b0f0-3afd3dbd9d49
⚠️ No act references found in case 103b8e60-39a2-4562-aa6b-f12cd44533c0
⚠️ No act references found in case f828899b-7f76-4343-9193-f5a47ff15f97
⚠️ No act references found in case e786c1b4-4f82-4c38-9644-445b4c0697ac
⚠️ No act references found in case a3830189-b11e-4c36-907c-7e47f403bf34
⚠️ No act references found in case 419c5dcb-d175-4752-a3f5-64af1b6e1e0c
⚠️ No act references found in case 0c195c82-11ab-44d5-b030-f05cbc4425cd
⚠️ No act references found in case 8a5a0c18-6299-4286-8b07-0bb27b305174
⚠️ No act references found in case cd114fef-26eb-4fe8-a413-e7f99aba93a2
⚠️ No act references found in case f19e49d6-b31c-4e12-baaf-06774f4a1281
⚠️ No act references found in case 2584ac4b-9ae7-4eba-8e76-2c04f2c42724
⚠️ No act references found in case 7d002dd1-0296-47cf-a18f-2cb516afd722
⚠️ No act references found in case 51b5d839-480d-4475-ba37-2ab848b21339
⚠️ No act references found in case 42ba7ebd-647c-4523-b38f-85ba31078f0e
⚠️ No act references found in case 1462c08b-e99f-441c-a0c8-0082f0d0362b
⚠️ No act references found in case d232ca12-d970-400b-be2d-0bd018ad149f
⚠️ No act references found in case 24360ecc-8aa7-4522-b1fc-ec164bc40f67
⚠️ No act references found in case 8958b993-e752-4487-90c5-9b8ad2b40041
⚠️ No act references found in case 02ed7b72-138a-4cf6-97e5-06b01322fb4c
⚠️ No act references found in case 6cd4527d-eb14-4720-b8b0-5e4558724d85
⚠️ No act references found in case b728e9fe-c4e6-4af3-9d37-231c87f9a25b
⚠️ No act references found in case b3961891-160d-4b90-be6b-37f6d4557b13
⚠️ No act references found in case 54878a96-d9fb-4932-9202-71a4adfa7f27
⚠️ No act references found in case c9b43180-4181-45a5-b5b1-e525aa39078f
⚠️ No act references found in case 70681e64-e605-48fe-b80c-b01877f41a46
⚠️ No act references found in case c67169d2-3402-4801-8d3f-c66d6f7ed467
⚠️ No act references found in case 1e56e882-7e06-4185-9eed-f8d37654308d
⚠️ No act references found in case c4f219e6-f570-4b3d-918e-173a1e3a0ff2
⚠️ No act references found in case 016a8461-93bb-4746-b66c-03ff62926220
⚠️ No act references found in case 00d8cbe8-f63a-46cb-b5c9-54b2a837e865
⚠️ No act references found in case 2c6fd630-cf2f-47ba-a4db-62b6c9a747de
⚠️ No act references found in case cbfbac6c-6bda-4c1d-ae8c-bb269147f892
⚠️ No act references found in case 4c49ad0a-788e-4f91-b1ca-6e3e62cb0c7d
⚠️ No act references found in case 6a033a80-f62c-46c2-9318-5e9f8f84d742
⚠️ No act references found in case 7dd4b269-39f3-47c7-899b-274438736d16
⚠️ No act references found in case 137c849c-00ee-4f17-81bc-77063bb0fc07
⚠️ No act references found in case 339386fe-fc6a-48cb-bb45-84773743f222
⚠️ No act references found in case 02d66939-df82-416a-8808-4a9961f4f67e
⚠️ No act references found in case 7acd3114-ab01-4dd8-aac1-0d4a01261eb6
⚠️ No act references found in case ace6a6cc-08e6-43ef-a3cf-c0eece10bf29
⚠️ No act references found in case 8d5b502b-356d-4074-baf1-aaf2884c9747
⚠️ No act references found in case 636d458f-f093-4a91-85ea-2922b4fcd365
⚠️ No act references found in case 8537a19e-7033-458b-8526-d95e998f1009
⚠️ No act references found in case 48154c88-e65a-4cd4-9c00-a4fab23fd439
⚠️ No act references found in case ba85a96d-4aa0-47f8-a771-719dd60e098b
⚠️ No act references found in case ac51a249-b354-4184-bb62-e928e314bdee
⚠️ No act references found in case 1358d3d2-883f-4651-9501-672f90d35d0c
⚠️ No act references found in case b7c9ae4a-e8bb-4161-a102-ca169acf8f50
⚠️ No act references found in case be9a541b-b881-4b62-993d-9c397cbd0e5c
⚠️ No act references found in case e24b725a-c058-4aee-9b91-ac3f4d1a213d
⚠️ No act references found in case 16eace40-ddb1-412c-becb-7cbdbea153bb
⚠️ No act references found in case b022485c-cd87-4f36-b25c-903ebadd30ce
⚠️ No act references found in case 59171a5f-4b4f-495c-8ee0-fa86a921550b
⚠️ No act references found in case 7640f61f-15a9-406a-bb5f-edc63fd77bfe
⚠️ No act references found in case 973e6bea-048c-46b9-b6dd-33603bf91ab3
⚠️ No act references found in case 30c46939-210f-44e1-8f99-a83e6029368e
⚠️ No act references found in case 3263ffaf-df7a-47fe-af37-4f891b4b7ea5
⚠️ No act references found in case 088935ba-85e3-4b4a-900b-acce56c85428
⚠️ No act references found in case 63a3bd22-bef3-4002-939c-c84da94a6578
⚠️ No act references found in case a2d0fa17-71e9-40d6-85ea-b1f4870d6ff5
⚠️ No act references found in case 3aae7340-441a-48b9-8c7c-cde5224698cc
⚠️ No act references found in case 83e106de-46a1-47e2-98c2-ff4150a19048
⚠️ No act references found in case 40067d14-1114-4102-ab12-1d00c6709162
⚠️ No act references found in case 52ad6b4c-6e43-425c-b5f5-f68713dfc263
⚠️ No act references found in case 43ed03d4-4a91-4473-8ef5-4450dc4d6f0e
⚠️ No act references found in case b0cab9f2-96e6-4d2e-8e46-d71f1046c702
⚠️ No act references found in case 72b1747a-c72c-47ef-ab3a-c7a5602e35d5
⚠️ No act references found in case 037b9a0b-478a-48aa-882d-fa1010e9ff3d
⚠️ No act references found in case f8769cff-e24e-43c7-82d9-5eec0b98634b
⚠️ No act references found in case 871541c0-c669-4500-82b3-d741aa44eab6
⚠️ No act references found in case f546e18c-f4c6-47b7-a661-93d946123989
⚠️ No act references found in case 9af3fa1c-fa09-4eb5-a3e2-95963d5ba2df
⚠️ No act references found in case bf4b97ea-7d5c-4853-9d71-a28dde2f9fcd
⚠️ No act references found in case 084636af-af08-4d22-9b3c-6b9e77be7af2
⚠️ No act references found in case e35e5313-1f07-45d9-a3fd-4af907a275e0
⚠️ No act references found in case 46eaa618-d565-4fe5-8ba1-111386d25f06
⚠️ No act references found in case 7ab30715-525b-456d-82bf-31247785dd3e
⚠️ No act references found in case 652e0d93-edcc-4614-86d5-79d939c84ddc
⚠️ No act references found in case ddfdad18-6bae-4ef0-a050-409c7e06ad56
⚠️ No act references found in case 3f9efaab-e509-496d-a217-bef80425e629
⚠️ No act references found in case 9a55fe67-814f-490b-ac7b-31389ab29832
⚠️ No act references found in case b6edfc59-c581-4307-9524-8eb9856f2f20
⚠️ No act references found in case 84892102-f616-467b-b200-54268daebb51
⚠️ No act references found in case 68ed48c1-1cef-4fda-8fd4-6655df7d82e5
⚠️ No act references found in case 36ea1973-407f-4ed9-98ee-c61be74ee345
⚠️ No act references found in case 5fc37e42-90ad-45bb-8e4a-d95ac24031bc
⚠️ No act references found in case 38a4a3c8-cdf9-4880-8aed-63bff8102d5d
⚠️ No act references found in case 64eb707d-b58f-4a7b-a6ea-543f53dea710
⚠️ No act references found in case ec07a8c3-5b30-4855-b487-7102bf3e4929
⚠️ No act references found in case 0b707d80-6fc3-444f-923c-0b6c0ef4a5ec
⚠️ No act references found in case 71f89e08-6559-4704-93b2-942a7a6f7a96
⚠️ No act references found in case 40ca1b1d-e166-4690-af42-a63fcc5d3354
⚠️ No act references found in case f8764064-1cca-4e58-9840-4519bc66c591
⚠️ No act references found in case 3f17f0ce-c436-4679-9c38-fc1ff8e89b84
⚠️ No act references found in case 20e77e40-0b70-421e-9d39-270a91aa04ba
⚠️ No act references found in case 4d7f4725-7dc3-4ada-819e-851b1b80efe8
⚠️ No act references found in case ba64c81b-94a2-40a9-8c19-bfc07f652de7
⚠️ No act references found in case e824acbe-06b4-43dd-92ae-ad86acbcd8b8
⚠️ No act references found in case e4199e93-a6b7-4107-8106-9e3af8fb17c6
⚠️ No act references found in case 74470f9f-edaf-4aff-98db-be4b1bbfb048
⚠️ No act references found in case cc9f69f6-39e8-4ef1-9e75-450881947ceb
⚠️ No act references found in case 70fc2e23-5d96-4205-8e79-b9ff79ad2706
⚠️ No act references found in case 9fc8b7ed-5f8a-4c5f-afc7-43db5880564f
⚠️ No act references found in case 463a364f-1bca-4a24-b67d-d464d3d5ba34
⚠️ No act references found in case 24131d4f-91d2-4b8d-aac5-e0bb7639fee9
⚠️ No act references found in case 8cf22862-8f51-4bf7-9c02-71eed259cb4a
⚠️ No act references found in case 4d4dba78-2314-490e-bd56-7a7135c1eeee
⚠️ No act references found in case e6b06dd7-c57c-4833-9d97-36fd9df4f565
⚠️ No act references found in case 82d256cd-3774-4539-94df-7ba9c4f71cf6
⚠️ No act references found in case e2c4b3c4-fff1-4ecd-9450-0b865526844f
⚠️ No act references found in case 3bd08cfb-9625-4bd2-9f3b-5ad63d7d381c
⚠️ No act references found in case 7672286d-5164-479c-8f35-1446a8db792c
⚠️ No act references found in case 34d120fb-3ec8-4c7d-aebb-a35d6a048e7a
⚠️ No act references found in case de19cda3-12dc-4f9f-a7f0-d5265a53986d
⚠️ No act references found in case ccd3f77f-9f56-4326-a2ba-065bcb8c6900
⚠️ No act references found in case 7a20a16c-6ade-467a-8a19-0fc81eb92ab4
⚠️ No act references found in case 0a099e5c-e94a-4230-baac-a8129264a248
⚠️ No act references found in case d31ecd45-c942-4c59-9d19-b890479d750f
⚠️ No act references found in case b237d0b8-83dc-42d3-9081-9ec6d0b1ec47
⚠️ No act references found in case 84cb1e50-d88c-4845-8f2c-47bc379d9639
⚠️ No act references found in case 6780067c-6cf3-48d0-881e-1fd58fe402df
⚠️ No act references found in case a159c031-2042-45ce-aaea-a5dde4146ab8
⚠️ No act references found in case 76a2098c-f073-41f9-b795-c4c9fed30fc0
⚠️ No act references found in case 93c68c74-8fb9-45a7-be24-9f2fe51a5870
⚠️ No act references found in case 086a4c8c-ec9c-4620-8f6c-71c62d9546ec
⚠️ No act references found in case ed913c97-631e-47de-8e23-0d8ee64835dc
⚠️ No act references found in case caa0633f-db74-4c47-9405-9e622b0394e0
⚠️ No act references found in case 5e1cb86d-11b0-4843-9b6b-614f761497c7
⚠️ No act references found in case 080b4d3d-3b9f-4d7a-90cf-8d457c8e64b9

,case_id,filename,raw_acts
0,8fb1373c-2b19-4df4-bbcc-40b0720dc9b3,hcc_0384_18_final_judgement_pdf.pdf,[]
1,f377d509-ea0d-4a2f-9e7a-4d2a14515d19,wrt_0471_19_pdf.pdf,[]
2,3f222e28-d9a0-452e-aa98-498d5656613e,ca_phc_0066_12_final_judgement_pdf.pdf,[]
3,9eaa002e-2133-40a3-97ec-3bf16d5829f8,cpa_0132_23_final_judgement_pdf.pdf,"[Release of Remand Prisoners Act,, No. 8 of 1991]"
4,2d8f6172-6e23-4841-8b6e-70952dfc1cdc,court_of_appeal_judgment_hcc_0184_17_pdf.pdf,"[Evidence (Special Provisions) Act, No. 32 of ..."
...,...,...,...
525,8aae1282-9448-4ade-9b70-8b0eb59eb80a,ca_writ_486_2021_1_pdf.pdf,[]
526,2cf9f0ee-1df2-44b2-a891-4415f9174e89,court_of_appeal_judgment_hcc_327_2019_pdf.pdf,[]
527,46985ee6-bf08-4b7d-a92c-bb83bbf5266e,ca_phc_apn_62_2017_final_judgment_pdf.pdf,"[Amendment Act, No. 10 of 1982]"
528,95885351-817c-4d60-97aa-206204a40420,ca_wrt_0088_19_pdf.pdf,[]
529,6430a362-68aa-4217-9797-2645d1e3baab,ca_wrt_0285_20_pdf.pdf,"[Universities Act,, No. 16 of 1978]"

In [8]:
# 🛠️ Cell 2: Act Standardizer Utility and Final Processing

import re
import pandas as pd

class ActStandardizer:
    """
    A utility class to parse raw act strings into a structured format,
    handling complex names with special provisions.
    """
    def __init__(self):
        # NEW REGEX: Designed to capture the main name, an optional parenthetical part,
        # the keyword, number, and year as separate groups.
        self.parsing_pattern = re.compile(
            # Group 1: The main name part (optional, non-greedy). Handles "bail act" or "Evidence".
            r'((?:[a-z\s]+)?)'
            # Group 2: The parenthetical part, e.g., "(special provision)" (optional).
            r'(?:\s*\((.*?)\))?'
            # Group 3: The keyword itself (e.g., "Act").
            r'\s*(Act|Code|Ordinance|Law|Regulation|Rules)'
            # Optional comma separator
            r'[,]+?\s*'
            # Group 4: The act number.
            r'(?:No\.?|Number)\s*(\d+)\s*'
            # Group 5: The act year.
            r'of\s*(\d{4})',
            re.IGNORECASE
        )

    def standardize(self, raw_act_text):
        """
        Parses a raw act string and returns a dictionary with a fully formatted name.
        """
        match = self.parsing_pattern.search(raw_act_text)

        if not match:
            # If the pattern fails entirely, mark as Unknown.
            return {
                "act_name": "Unknown",
                "act_number": "N/A",
                "year": "N/A"
            }

        # --- Extract all components from the regex match ---
        main_name_part = match.group(1)
        parenthetical_part = match.group(2)
        keyword = match.group(3)
        number = match.group(4)
        year = match.group(5)

        # --- Build the final formatted name string ---
        final_name_parts = []

        # Add the main name part if it exists
        if main_name_part and main_name_part.strip():
            final_name_parts.append(main_name_part.strip().title())

        # Always add the keyword (e.g., "Act", "Code")
        # final_name_parts.append(keyword.capitalize())

        # If a parenthetical part was found, format it and add it
        if parenthetical_part and parenthetical_part.strip():
            final_name_parts.append(f"[{parenthetical_part.strip().lower()}]")

        # Join the parts to create the name. If no name part was found,
        # the list will just contain the keyword, e.g., ['Act'].
        final_name = ' '.join(final_name_parts).lower()
        final_name = re.sub(r'\s+', '-', final_name)


        # If the final name is just the keyword, it means no descriptive name was found.
        if final_name.lower() == keyword.lower():
            final_name = "unknown"

        return {
            "act_name": final_name,
            "act_number": number,
            "year": year
        }

# --- Standardization Process ---
standardizer = ActStandardizer()
final_structured_list = []

print("\nStandardizing extracted acts into the final format...")

# Check if the input data from the previous cell exists
if 'raw_case_act_map' in locals() and raw_case_act_map:
    for entry in raw_case_act_map:
        case_id = entry["case_id"]
        if not entry["raw_acts"]:
          print(f"⚠️ No raw acts found for entry: {entry['case_id']}")
          final_structured_list.append({
              "case_id": case_id,
              "filename":entry["filename"],
              "standardized_act": None
          })

        for raw_act in entry["raw_acts"]:
            # Get the structured dictionary with the fully formatted name
            structured_act = standardizer.standardize(raw_act)
            filename = entry["filename"]

            # Format the final string as "Name_X_YYYY"
            formatted_string = f"{structured_act['act_name']}_{structured_act['act_number']}_{structured_act['year']}"

            final_structured_list.append({
                "case_id": case_id,
                "filename":filename,
                "standardized_act": formatted_string
            })


    final_df = pd.DataFrame(final_structured_list)

    grouped_df = final_df.groupby("case_id").agg({
        "standardized_act": list,
        "filename": "first"
    }).reset_index()

    # Show the final results
    print("✅ Standardization complete.")
    print("\n📋 Final Standardized Act Data (Grouped by Case ID):")
    display(grouped_df)

else:
    print("⚠️ No raw act data (`raw_case_act_map`) found to process. Please run the extraction cell first.")

Standardizing extracted acts into the final format...
⚠️ No raw acts found for entry: 8fb1373c-2b19-4df4-bbcc-40b0720dc9b3
⚠️ No raw acts found for entry: f377d509-ea0d-4a2f-9e7a-4d2a14515d19
⚠️ No raw acts found for entry: 3f222e28-d9a0-452e-aa98-498d5656613e
⚠️ No raw acts found for entry: eaaf5922-459d-46c6-8a6d-7d943cf59802
⚠️ No raw acts found for entry: 8a23d9c9-b5b6-4c47-87ef-ab9d38ab5272
⚠️ No raw acts found for entry: 70e90de1-f93f-48d9-840a-6a2b1b067278
⚠️ No raw acts found for entry: 8a1844b8-851e-4ad5-ae21-ce790eb9c199
⚠️ No raw acts found for entry: 1879977a-a086-41c6-a1e3-5fc4fcf05ab1
⚠️ No raw acts found for entry: 1fd3711c-cee9-4d59-9023-a32cd006f8d1
⚠️ No raw acts found for entry: a8214375-4576-411e-9849-fbb225ce6f16
⚠️ No raw acts found for entry: 0b62012f-a1fb-435b-80d5-2a867b52ad09
⚠️ No raw acts found for entry: 2acb30b0-4625-44c1-8e66-4224f774d4bf
⚠️ No raw acts found for entry: 766f067d-f06a-4953-bbe3-444a2c498bd6
⚠️ No raw acts found for entry: e18d4705-26a5-4c70-9216-5542b8693941
⚠️ No raw acts found for entry: 87059a23-5b75-4105-a616-cf5ecf1fd0df
⚠️ No raw acts found for entry: ac043c15-2add-4c59-836b-65a5d08869c9
⚠️ No raw acts found for entry: 5c5d435b-9a04-4982-9315-d86e724ee2ff
⚠️ No raw acts found for entry: cf7603c3-eaac-4afc-ba52-108d869271fd
⚠️ No raw acts found for entry: e1c74410-95b5-4673-8e18-3c1e07808fea
⚠️ No raw acts found for entry: b8e84465-1397-4497-ba67-52f06e90ca24
⚠️ No raw acts found for entry: 11a0f7fd-e554-43cf-874d-58d3ccf2ee44
⚠️ No raw acts found for entry: 478912e5-e6ae-4331-913e-67807f3a190d
⚠️ No raw acts found for entry: 9046e351-ece0-4ec9-befb-b510ad75ba35
⚠️ No raw acts found for entry: 8ed9ea40-b285-43f5-a3b3-85342677cf5e
⚠️ No raw acts found for entry: ca849a2a-fb07-41dc-96ee-6da806509357
⚠️ No raw acts found for entry: 49cc1460-8ed5-434e-b19e-85a598e5c0dd
⚠️ No raw acts found for entry: e91375a2-16eb-40d9-89ed-c00a58f183c9
⚠️ No raw acts found for entry: 4ea5ae9c-ecd2-42cf-8001-6e843b357b65
⚠️ No raw acts found for entry: 7f992d67-e4c4-4e12-8cd3-2b8c19fae301
⚠️ No raw acts found for entry: a2db6889-5eef-457b-a6d5-ca043fd23207
⚠️ No raw acts found for entry: 9c422859-f88d-4ac1-8cb5-862c47f44517
⚠️ No raw acts found for entry: 82763803-d062-4b9a-9ab0-6cdfbfb16082
⚠️ No raw acts found for entry: 64d3c8d1-e0b6-45a7-92fc-76d9c5c11445
⚠️ No raw acts found for entry: a111fc60-fcf9-4e9d-b2d5-dfe223d04832
⚠️ No raw acts found for entry: 9db42518-a10a-4d5b-8ba3-fd2d7110a46d
⚠️ No raw acts found for entry: 8615cb05-fa9e-4e8f-906d-3dafa3419e7e
⚠️ No raw acts found for entry: 4a034773-c685-408f-8c3e-d4cb40c5049c
⚠️ No raw acts found for entry: 78910e92-0665-4c1a-bf51-6d49d87457c3
⚠️ No raw acts found for entry: e71ab068-62d0-4192-ac11-958c6b2dddd7
⚠️ No raw acts found for entry: 237700f2-6252-40e4-9d16-e1e05ebfbfe5
⚠️ No raw acts found for entry: 997893ef-099d-40a5-903b-1d5ca3a77d89
⚠️ No raw acts found for entry: b43a5cae-2a7b-43c5-a658-921752cb2f24
⚠️ No raw acts found for entry: 6b397e17-67f0-4a49-8ca9-64903f5745db
⚠️ No raw acts found for entry: be41a342-ff76-4b43-b574-c016ceb99e5a
⚠️ No raw acts found for entry: dc6ff29a-02b1-4d34-8567-498ee09e229b
⚠️ No raw acts found for entry: e32dd0fd-caa5-4e1d-a4ac-7a99af25bd39
⚠️ No raw acts found for entry: 8354a3ab-e548-477e-8ff6-efc40917a171
⚠️ No raw acts found for entry: e1a554e3-5ef3-49a6-889a-cf1abd13fb40
⚠️ No raw acts found for entry: bc8308c7-7abe-4250-a07c-2dd913c324b2
⚠️ No raw acts found for entry: 1225feb1-0f30-46ee-bd1c-5180eeb5c601
⚠️ No raw acts found for entry: aad05a37-c875-47bc-b999-9c7d7f78a36d
⚠️ No raw acts found for entry: 1e191d25-804a-4089-9fe7-a3db5f355b52
⚠️ No raw acts found for entry: 08f48d45-c717-4ac5-8626-3372918d07aa
⚠️ No raw acts found for entry: c24336e5-676c-44db-94b8-ca4cc418f7fa
⚠️ No raw acts found for entry: c83188b6-db26-4881-be1f-7001df170751
⚠️ No raw acts found for entry: 230029f2-0f9c-436c-9b85-7a3093788ab7
⚠️ No raw acts found for entry: feef7510-85d1-4008-90cd-d1bf610c3f1d
⚠️ No raw acts found for entry: 4f732cca-c1a1-444b-a9cf-4df2d867fb65
⚠️ No raw acts found for entry: 28ccd4da-82a9-44d5-9097-3f2ccc1b4d17
⚠️ No raw acts found for entry: 7b8e6f55-246e-4329-97bd-4834de5d6228
⚠️ No raw acts found for entry: 8becedd8-3b50-4977-b7cb-733af96669ae
⚠️ No raw acts found for entry: fd50c234-c49e-440d-9748-3962e204acdf
⚠️ No raw acts found for entry: a096ca11-1976-4606-afd8-6fda8566560d
⚠️ No raw acts found for entry: b13bfa02-76b8-437c-b587-61b0c56aa04a
⚠️ No raw acts found for entry: 4d06398d-977a-4129-8661-ff358f3c5487
⚠️ No raw acts found for entry: 12949064-b074-471c-8a17-d5d6bd6597f8
⚠️ No raw acts found for entry: c4ef11b6-f7a6-4c95-ad35-4ea23de886bf
⚠️ No raw acts found for entry: ba34336d-c194-4c8d-a873-c07d6de7ed01
⚠️ No raw acts found for entry: 4286ec96-bcdc-4f8f-ab05-26370423dbc0
⚠️ No raw acts found for entry: 1c188f6d-3832-4641-8f4a-a19c747cc0b5
⚠️ No raw acts found for entry: 7b6aa5f6-c52c-4eec-8b58-eb95316b4072
⚠️ No raw acts found for entry: baf6be9b-ad31-4da2-976c-f756ec350021
⚠️ No raw acts found for entry: c01c70c7-6bd3-4baf-9b14-4433f09c25c4
⚠️ No raw acts found for entry: d9568be1-3aa6-4596-858a-1e9d9b18ae4c
⚠️ No raw acts found for entry: a634ab9a-1a3b-4ad1-bfda-e7ff4bb5f101
⚠️ No raw acts found for entry: 239785d6-2cdd-46bc-a88f-80354bf5bb30
⚠️ No raw acts found for entry: 01678304-fafe-410c-93c4-9eb6b147acaf
⚠️ No raw acts found for entry: 41d80e88-2173-4d7d-abd7-329807e73477
⚠️ No raw acts found for entry: 4ada41bf-3e2a-4107-aa78-0486503fb289
⚠️ No raw acts found for entry: d179cfda-c0e1-4ad4-93d1-6a9af95a3722
⚠️ No raw acts found for entry: 082359b1-0049-4a61-a436-51f5583832ac
⚠️ No raw acts found for entry: a7bbb81f-e817-4ae7-a265-3a3957547cb1
⚠️ No raw acts found for entry: 0728263e-0343-4101-908c-9aaaec356ea4
⚠️ No raw acts found for entry: 71a4f042-ec3f-4056-988e-9a28d4d3447e
⚠️ No raw acts found for entry: 451a21c1-c07b-4b76-aba2-084b635eef66
⚠️ No raw acts found for entry: bab543fa-d1ef-4718-bbf4-a28d6077d5ab
⚠️ No raw acts found for entry: fb842387-f41a-49bd-a31d-c287210ad0b2
⚠️ No raw acts found for entry: c2130377-fb03-41d5-85f1-980b613c65d9
⚠️ No raw acts found for entry: 471b5e7b-9283-4527-b7ca-be576c990cca
⚠️ No raw acts found for entry: aed75516-fba6-4af7-94fc-838145f9c8df
⚠️ No raw acts found for entry: 24b89c2c-6ad8-477d-ae6c-ca05199bef91
⚠️ No raw acts found for entry: 064f53c2-43b8-43bf-af14-4677be56b484
⚠️ No raw acts found for entry: af2ad53c-541a-4f0e-a6a9-05acde022dd7
⚠️ No raw acts found for entry: 935f5861-89b2-45ad-ba11-a850b2a6a212
⚠️ No raw acts found for entry: 0b03db14-7e1c-41d1-b75f-bc930a9702c7
⚠️ No raw acts found for entry: ef2f8041-7870-471f-ae54-98916377b35e
⚠️ No raw acts found for entry: 670aacd2-2076-4536-b196-8cb77ca5822d
⚠️ No raw acts found for entry: 34383139-c8e3-48a4-b261-fb6ce0790393
⚠️ No raw acts found for entry: 95404603-658d-4e41-9858-2c51f849f01a
⚠️ No raw acts found for entry: 75ce9b97-3987-40a7-89ec-8047db3fdea7
⚠️ No raw acts found for entry: 295ab45e-7da3-4336-8698-ca0c4ec75e4a
⚠️ No raw acts found for entry: c305cef2-a189-4d17-82f1-dc1577b3ea6a
⚠️ No raw acts found for entry: ae11b754-4c97-43c5-8ed1-03f3c3382dbc
⚠️ No raw acts found for entry: d37f1d4e-83ff-49b8-a270-281aad401807
⚠️ No raw acts found for entry: 74463333-390d-4f93-a514-b8874262efd0
⚠️ No raw acts found for entry: 19ffe04a-fc8a-41aa-8ec4-f0ca0266a8f9
⚠️ No raw acts found for entry: 5437caf3-58c8-4f10-b286-11e19c2f697a
⚠️ No raw acts found for entry: 9a0c6c03-945f-48ba-9cde-0bfd81ff4718
⚠️ No raw acts found for entry: 1b895da5-766d-4549-9f2c-111b7dd050ee
⚠️ No raw acts found for entry: f4ee2a56-59b2-4601-91fb-af5cbf2afd30
⚠️ No raw acts found for entry: 3cbc61c2-6c60-45c1-aa83-6d4911f1a80b
⚠️ No raw acts found for entry: 80dccf2c-b709-45b4-bdc4-b38d1d9bca28
⚠️ No raw acts found for entry: 07ce6884-2cc9-4001-8c00-dc6c3c22f548
⚠️ No raw acts found for entry: a12afdc7-dba0-4325-8ff3-dc5cc785c22a
⚠️ No raw acts found for entry: 4b19cc5d-b4a1-44a1-8d2a-22925600e873
⚠️ No raw acts found for entry: 80f4e883-a2b3-4391-9812-5bb2ade2ae44
⚠️ No raw acts found for entry: 4f8f25df-dd87-4a26-9f47-703367d31eda
⚠️ No raw acts found for entry: d88f805b-5eea-4280-a8cc-6fdfc2181807
⚠️ No raw acts found for entry: f23752eb-37cd-47dd-8986-b22b19836ebe
⚠️ No raw acts found for entry: f78ad6c0-25a6-4313-9ef4-acdcf13f9984
⚠️ No raw acts found for entry: e3e4b968-7b4a-45da-8c31-72f04b2876a5
⚠️ No raw acts found for entry: 3820f8f0-fb08-4b00-8083-dcdf15feb13e
⚠️ No raw acts found for entry: 05d738bb-6b65-4ab6-87dc-9430ac1db158
⚠️ No raw acts found for entry: 2b8380b7-f175-4a71-91b1-9fb9d7dc4758
⚠️ No raw acts found for entry: d8c02994-c781-41f7-b5e7-9bc6c6916371
⚠️ No raw acts found for entry: a7eb4b83-8a0a-4f26-bce9-6f43bcd67469
⚠️ No raw acts found for entry: e18615e5-3c60-45fd-ad38-430b739a3efb
⚠️ No raw acts found for entry: 262aedba-2fcc-49a5-b535-d325ae576489
⚠️ No raw acts found for entry: 4a1ace84-ef95-4a42-9794-913fc2eef79b
⚠️ No raw acts found for entry: 87666ed1-8f7c-4e5d-9f52-b7c1307188a0
⚠️ No raw acts found for entry: 6b5ad828-993f-4558-9413-7f618b777058
⚠️ No raw acts found for entry: ec5b0f83-bcca-4d7e-a788-b1e79ce87768
⚠️ No raw acts found for entry: cf6ea2c0-c0f4-4fe6-9f84-c554e86d410e
⚠️ No raw acts found for entry: 45badd58-4c55-4219-9f61-e7e6b7ba0192
⚠️ No raw acts found for entry: ad3f408d-4361-465a-a0bd-00192acac37a
⚠️ No raw acts found for entry: 072d36cd-d3b8-473d-8f1c-008924ee8cbf
⚠️ No raw acts found for entry: dbd82ae2-7efd-48f4-a31c-5658669c0c41
⚠️ No raw acts found for entry: 143f0a1a-686b-4cba-88d9-1865cec05e5f
⚠️ No raw acts found for entry: 0e292e21-9b0b-4b5e-8cd1-9f10400a1f32
⚠️ No raw acts found for entry: 2c79bbf9-aedb-4d42-9dbc-c155c6c58941
⚠️ No raw acts found for entry: d2344814-e35a-4569-b34b-d223802ba2d0
⚠️ No raw acts found for entry: 5322bcba-f846-4674-bcdd-b429f672a544
⚠️ No raw acts found for entry: 12371d9b-4dac-4c40-9487-4c1f759ad9f8
⚠️ No raw acts found for entry: b0e99071-e96f-4849-9b34-b5be6751de86
⚠️ No raw acts found for entry: 56753735-24a6-4c13-bbcc-b8a217cf3a15
⚠️ No raw acts found for entry: 9312caf3-c75f-476d-994e-6ae9ca9b5617
⚠️ No raw acts found for entry: b35d1893-71f1-484b-bbf0-2a0ce282e928
⚠️ No raw acts found for entry: 3bb0f104-b93d-4093-a7d2-97f5139b60ab
⚠️ No raw acts found for entry: f61db562-24bf-42a2-b0f0-3afd3dbd9d49
⚠️ No raw acts found for entry: 103b8e60-39a2-4562-aa6b-f12cd44533c0
⚠️ No raw acts found for entry: f828899b-7f76-4343-9193-f5a47ff15f97
⚠️ No raw acts found for entry: e786c1b4-4f82-4c38-9644-445b4c0697ac
⚠️ No raw acts found for entry: a3830189-b11e-4c36-907c-7e47f403bf34
⚠️ No raw acts found for entry: 419c5dcb-d175-4752-a3f5-64af1b6e1e0c
⚠️ No raw acts found for entry: 0c195c82-11ab-44d5-b030-f05cbc4425cd
⚠️ No raw acts found for entry: 8a5a0c18-6299-4286-8b07-0bb27b305174
⚠️ No raw acts found for entry: cd114fef-26eb-4fe8-a413-e7f99aba93a2
⚠️ No raw acts found for entry: f19e49d6-b31c-4e12-baaf-06774f4a1281
⚠️ No raw acts found for entry: 2584ac4b-9ae7-4eba-8e76-2c04f2c42724
⚠️ No raw acts found for entry: 7d002dd1-0296-47cf-a18f-2cb516afd722
⚠️ No raw acts found for entry: 51b5d839-480d-4475-ba37-2ab848b21339
⚠️ No raw acts found for entry: 42ba7ebd-647c-4523-b38f-85ba31078f0e
⚠️ No raw acts found for entry: 1462c08b-e99f-441c-a0c8-0082f0d0362b
⚠️ No raw acts found for entry: d232ca12-d970-400b-be2d-0bd018ad149f
⚠️ No raw acts found for entry: 24360ecc-8aa7-4522-b1fc-ec164bc40f67
⚠️ No raw acts found for entry: 8958b993-e752-4487-90c5-9b8ad2b40041
⚠️ No raw acts found for entry: 02ed7b72-138a-4cf6-97e5-06b01322fb4c
⚠️ No raw acts found for entry: 6cd4527d-eb14-4720-b8b0-5e4558724d85
⚠️ No raw acts found for entry: b728e9fe-c4e6-4af3-9d37-231c87f9a25b
⚠️ No raw acts found for entry: b3961891-160d-4b90-be6b-37f6d4557b13
⚠️ No raw acts found for entry: 54878a96-d9fb-4932-9202-71a4adfa7f27
⚠️ No raw acts found for entry: c9b43180-4181-45a5-b5b1-e525aa39078f
⚠️ No raw acts found for entry: 70681e64-e605-48fe-b80c-b01877f41a46
⚠️ No raw acts found for entry: c67169d2-3402-4801-8d3f-c66d6f7ed467
⚠️ No raw acts found for entry: 1e56e882-7e06-4185-9eed-f8d37654308d
⚠️ No raw acts found for entry: c4f219e6-f570-4b3d-918e-173a1e3a0ff2
⚠️ No raw acts found for entry: 016a8461-93bb-4746-b66c-03ff62926220
⚠️ No raw acts found for entry: 00d8cbe8-f63a-46cb-b5c9-54b2a837e865
⚠️ No raw acts found for entry: 2c6fd630-cf2f-47ba-a4db-62b6c9a747de
⚠️ No raw acts found for entry: cbfbac6c-6bda-4c1d-ae8c-bb269147f892
⚠️ No raw acts found for entry: 4c49ad0a-788e-4f91-b1ca-6e3e62cb0c7d
⚠️ No raw acts found for entry: 6a033a80-f62c-46c2-9318-5e9f8f84d742
⚠️ No raw acts found for entry: 7dd4b269-39f3-47c7-899b-274438736d16
⚠️ No raw acts found for entry: 137c849c-00ee-4f17-81bc-77063bb0fc07
⚠️ No raw acts found for entry: 339386fe-fc6a-48cb-bb45-84773743f222
⚠️ No raw acts found for entry: 02d66939-df82-416a-8808-4a9961f4f67e
⚠️ No raw acts found for entry: 7acd3114-ab01-4dd8-aac1-0d4a01261eb6
⚠️ No raw acts found for entry: ace6a6cc-08e6-43ef-a3cf-c0eece10bf29
⚠️ No raw acts found for entry: 8d5b502b-356d-4074-baf1-aaf2884c9747
⚠️ No raw acts found for entry: 636d458f-f093-4a91-85ea-2922b4fcd365
⚠️ No raw acts found for entry: 8537a19e-7033-458b-8526-d95e998f1009
⚠️ No raw acts found for entry: 48154c88-e65a-4cd4-9c00-a4fab23fd439
⚠️ No raw acts found for entry: ba85a96d-4aa0-47f8-a771-719dd60e098b
⚠️ No raw acts found for entry: ac51a249-b354-4184-bb62-e928e314bdee
⚠️ No raw acts found for entry: 1358d3d2-883f-4651-9501-672f90d35d0c
⚠️ No raw acts found for entry: b7c9ae4a-e8bb-4161-a102-ca169acf8f50
⚠️ No raw acts found for entry: be9a541b-b881-4b62-993d-9c397cbd0e5c
⚠️ No raw acts found for entry: e24b725a-c058-4aee-9b91-ac3f4d1a213d
⚠️ No raw acts found for entry: 16eace40-ddb1-412c-becb-7cbdbea153bb
⚠️ No raw acts found for entry: b022485c-cd87-4f36-b25c-903ebadd30ce
⚠️ No raw acts found for entry: 59171a5f-4b4f-495c-8ee0-fa86a921550b
⚠️ No raw acts found for entry: 7640f61f-15a9-406a-bb5f-edc63fd77bfe
⚠️ No raw acts found for entry: 973e6bea-048c-46b9-b6dd-33603bf91ab3
⚠️ No raw acts found for entry: 30c46939-210f-44e1-8f99-a83e6029368e
⚠️ No raw acts found for entry: 3263ffaf-df7a-47fe-af37-4f891b4b7ea5
⚠️ No raw acts found for entry: 088935ba-85e3-4b4a-900b-acce56c85428
⚠️ No raw acts found for entry: 63a3bd22-bef3-4002-939c-c84da94a6578
⚠️ No raw acts found for entry: a2d0fa17-71e9-40d6-85ea-b1f4870d6ff5
⚠️ No raw acts found for entry: 3aae7340-441a-48b9-8c7c-cde5224698cc
⚠️ No raw acts found for entry: 83e106de-46a1-47e2-98c2-ff4150a19048
⚠️ No raw acts found for entry: 40067d14-1114-4102-ab12-1d00c6709162
⚠️ No raw acts found for entry: 52ad6b4c-6e43-425c-b5f5-f68713dfc263
⚠️ No raw acts found for entry: 43ed03d4-4a91-4473-8ef5-4450dc4d6f0e
⚠️ No raw acts found for entry: b0cab9f2-96e6-4d2e-8e46-d71f1046c702
⚠️ No raw acts found for entry: 72b1747a-c72c-47ef-ab3a-c7a5602e35d5
⚠️ No raw acts found for entry: 037b9a0b-478a-48aa-882d-fa1010e9ff3d
⚠️ No raw acts found for entry: f8769cff-e24e-43c7-82d9-5eec0b98634b
⚠️ No raw acts found for entry: 871541c0-c669-4500-82b3-d741aa44eab6
⚠️ No raw acts found for entry: f546e18c-f4c6-47b7-a661-93d946123989
⚠️ No raw acts found for entry: 9af3fa1c-fa09-4eb5-a3e2-95963d5ba2df
⚠️ No raw acts found for entry: bf4b97ea-7d5c-4853-9d71-a28dde2f9fcd
⚠️ No raw acts found for entry: 084636af-af08-4d22-9b3c-6b9e77be7af2
⚠️ No raw acts found for entry: e35e5313-1f07-45d9-a3fd-4af907a275e0
⚠️ No raw acts found for entry: 46eaa618-d565-4fe5-8ba1-111386d25f06
⚠️ No raw acts found for entry: 7ab30715-525b-456d-82bf-31247785dd3e
⚠️ No raw acts found for entry: 652e0d93-edcc-4614-86d5-79d939c84ddc
⚠️ No raw acts found for entry: ddfdad18-6bae-4ef0-a050-409c7e06ad56
⚠️ No raw acts found for entry: 3f9efaab-e509-496d-a217-bef80425e629
⚠️ No raw acts found for entry: 9a55fe67-814f-490b-ac7b-31389ab29832
⚠️ No raw acts found for entry: b6edfc59-c581-4307-9524-8eb9856f2f20
⚠️ No raw acts found for entry: 84892102-f616-467b-b200-54268daebb51
⚠️ No raw acts found for entry: 68ed48c1-1cef-4fda-8fd4-6655df7d82e5
⚠️ No raw acts found for entry: 36ea1973-407f-4ed9-98ee-c61be74ee345
⚠️ No raw acts found for entry: 5fc37e42-90ad-45bb-8e4a-d95ac24031bc
⚠️ No raw acts found for entry: 38a4a3c8-cdf9-4880-8aed-63bff8102d5d
⚠️ No raw acts found for entry: 64eb707d-b58f-4a7b-a6ea-543f53dea710
⚠️ No raw acts found for entry: ec07a8c3-5b30-4855-b487-7102bf3e4929
⚠️ No raw acts found for entry: 0b707d80-6fc3-444f-923c-0b6c0ef4a5ec
⚠️ No raw acts found for entry: 71f89e08-6559-4704-93b2-942a7a6f7a96
⚠️ No raw acts found for entry: 40ca1b1d-e166-4690-af42-a63fcc5d3354
⚠️ No raw acts found for entry: f8764064-1cca-4e58-9840-4519bc66c591
⚠️ No raw acts found for entry: 3f17f0ce-c436-4679-9c38-fc1ff8e89b84
⚠️ No raw acts found for entry: 20e77e40-0b70-421e-9d39-270a91aa04ba
⚠️ No raw acts found for entry: 4d7f4725-7dc3-4ada-819e-851b1b80efe8
⚠️ No raw acts found for entry: ba64c81b-94a2-40a9-8c19-bfc07f652de7
⚠️ No raw acts found for entry: e824acbe-06b4-43dd-92ae-ad86acbcd8b8
⚠️ No raw acts found for entry: e4199e93-a6b7-4107-8106-9e3af8fb17c6
⚠️ No raw acts found for entry: 74470f9f-edaf-4aff-98db-be4b1bbfb048
⚠️ No raw acts found for entry: cc9f69f6-39e8-4ef1-9e75-450881947ceb
⚠️ No raw acts found for entry: 70fc2e23-5d96-4205-8e79-b9ff79ad2706
⚠️ No raw acts found for entry: 9fc8b7ed-5f8a-4c5f-afc7-43db5880564f
⚠️ No raw acts found for entry: 463a364f-1bca-4a24-b67d-d464d3d5ba34
⚠️ No raw acts found for entry: 24131d4f-91d2-4b8d-aac5-e0bb7639fee9
⚠️ No raw acts found for entry: 8cf22862-8f51-4bf7-9c02-71eed259cb4a
⚠️ No raw acts found for entry: 4d4dba78-2314-490e-bd56-7a7135c1eeee
⚠️ No raw acts found for entry: e6b06dd7-c57c-4833-9d97-36fd9df4f565
⚠️ No raw acts found for entry: 82d256cd-3774-4539-94df-7ba9c4f71cf6
⚠️ No raw acts found for entry: e2c4b3c4-fff1-4ecd-9450-0b865526844f
⚠️ No raw acts found for entry: 3bd08cfb-9625-4bd2-9f3b-5ad63d7d381c
⚠️ No raw acts found for entry: 7672286d-5164-479c-8f35-1446a8db792c
⚠️ No raw acts found for entry: 34d120fb-3ec8-4c7d-aebb-a35d6a048e7a
⚠️ No raw acts found for entry: de19cda3-12dc-4f9f-a7f0-d5265a53986d
⚠️ No raw acts found for entry: ccd3f77f-9f56-4326-a2ba-065bcb8c6900
⚠️ No raw acts found for entry: 7a20a16c-6ade-467a-8a19-0fc81eb92ab4
⚠️ No raw acts found for entry: 0a099e5c-e94a-4230-baac-a8129264a248
⚠️ No raw acts found for entry: d31ecd45-c942-4c59-9d19-b890479d750f
⚠️ No raw acts found for entry: b237d0b8-83dc-42d3-9081-9ec6d0b1ec47
⚠️ No raw acts found for entry: 84cb1e50-d88c-4845-8f2c-47bc379d9639
⚠️ No raw acts found for entry: 6780067c-6cf3-48d0-881e-1fd58fe402df
⚠️ No raw acts found for entry: a159c031-2042-45ce-aaea-a5dde4146ab8
⚠️ No raw acts found for entry: 76a2098c-f073-41f9-b795-c4c9fed30fc0
⚠️ No raw acts found for entry: 93c68c74-8fb9-45a7-be24-9f2fe51a5870
⚠️ No raw acts found for entry: 086a4c8c-ec9c-4620-8f6c-71c62d9546ec
⚠️ No raw acts found for entry: ed913c97-631e-47de-8e23-0d8ee64835dc
⚠️ No raw acts found for entry: caa0633f-db74-4c47-9405-9e622b0394e0
⚠️ No raw acts found for entry: 5e1cb86d-11b0-4843-9b6b-614f761497c7
⚠️ No raw acts found for entry: 080b4d3d-3b9f-4d7a-90cf-8d457c8e64b9
⚠️ No raw acts found for entry: c7a399d2-3a3a-4150-b2af-53c7d970678f
⚠️ No raw acts found for entry: 0a481a81-ba1a-49c8-bc56-a9c7b150250d
⚠️ No raw acts found for entry: af4b1fac-5ec8-48f3-b411-9c2d435b1197
⚠️ No raw acts found for entry: b9f49a37-e64a-42ab-a192-2d12a58ae146
⚠️ No raw acts found for entry: 2b8c4a66-76ef-4d02-bc62-40b50848f4e0
⚠️ No raw acts found for entry: fdc75ff5-b96f-4310-ac2d-967d2c679202
⚠️ No raw acts found for entry: 15725649-ae6b-46d5-ba95-0fef0770d171
⚠️ No raw acts found for entry: 9cf8d540-f5e4-4422-a494-32dfaa13eb3f
⚠️ No raw acts found for entry: 7be764ab-3659-403a-98cd-dbdeb9a725f4
⚠️ No raw acts found for entry: 9c0310ec-86b9-4ff7-9120-ff0865e23460
⚠️ No raw acts found for entry: bc9c75bd-5697-41cc-a7a7-fd8ad3b918e7
⚠️ No raw acts found for entry: 84166215-f408-45f7-b778-5a6fd4c32ae9

,case_id,standardized_act,filename
0,00d8cbe8-f63a-46cb-b5c9-54b2a837e865,[None],ca_hcc_0093_18_pdf.pdf
1,01678304-fafe-410c-93c4-9eb6b147acaf,[None],ca_cpa_0097_23_pdf.pdf
2,016a8461-93bb-4746-b66c-03ff62926220,[None],ca_hcc_0352_19_pdf.pdf
3,01bf4783-e054-4efc-929e-4feb4700d4f8,[pradeshiyasabhas_15_1987],wrt_151_23_judgment_pdf.pdf
4,01f89a02-5e35-4d26-ad0e-8bfd4abe138a,[None],wrt_334_22_judgment_pdf.pdf
...,...,...,...
525,fd50c234-c49e-440d-9748-3962e204acdf,[None],ca_237_2017_pdf.pdf
526,fd8b91aa-2dfd-446b-84f4-0c9b84c6bbbc,[code-of-criminal-procedure_15_1979],court_of_appeal_judgment_hcc_0160_22_pdf.pdf
527,fdc75ff5-b96f-4310-ac2d-967d2c679202,[None],wrt_436_22_judgment_pdf.pdf
528,fddb7e21-d879-46cf-b199-ed7303f03cf5,[None],ca_hcc_0255_256_18_pdf.pdf
529,feef7510-85d1-4008-90cd-d1bf610c3f1d,[None],wrt_0319_17_edited_1_pdf.pdf

In [9]:
# 🧠 Neo4j Connector Class

class Neo4jConnector:
    def __init__(self, uri, user, password):
        self.driver = GraphDatabase.driver(uri, auth=(user, password))

    def close(self):
        """Closes the database connection."""
        if self.driver:
            self.driver.close()

    def verify_connection(self):
        """Verifies and prints the connection status."""
        self.driver.verify_connectivity()
        print("✅ Connection to Neo4j AuraDB verified successfully.")

    def push_case_with_acts(self, case_id, filename, acts):
        """Pushes a single case and its act relationships to the graph."""
        with self.driver.session(database="neo4j") as session:
            session.execute_write(self._create_graph_tx, case_id, filename, acts)

    @staticmethod
    def _create_graph_tx(tx, case_id, filename, acts):
    # Create or update the Case node with filename
       tx.run(
        """
        MERGE (c:Case {doc_id: $case_id})
        SET c.filename = $filename
        """, case_id=case_id, filename=filename
       )

    # Create Act nodes and relationships
       if acts:
        tx.run(
            """
            UNWIND $acts AS act_name
            MATCH (c:Case {doc_id: $case_id})
            MERGE (a:Act {std_id: act_name})
            MERGE (c)-[:REFERS_TO]->(a)
            SET a.doc_id = $case_id
            """,
            case_id=case_id,
            acts=acts
        )


    def set_case_metadata(self, case_id, metadata: dict):
        """Sets or updates metadata for a given Case node."""
        with self.driver.session(database="neo4j") as session:
            session.execute_write(self._update_metadata_tx, case_id, metadata)

    @staticmethod
    def _update_metadata_tx(tx, case_id, metadata: dict):
        # Build a dynamic Cypher SET clause for all metadata keys
        print(metadata)
        set_clause = ', '.join([f"c.{key} = ${key}" for key in metadata])
        parameters = {"case_id": case_id, **metadata}

        query = f"""
        MATCH (c:Case {{doc_id: $case_id}})
        SET {set_clause}
        """

        tx.run(query, parameters)


    def get_acts_for_case(self, case_id):
        """Queries for a case and returns a list of its referred act names."""
        with self.driver.session(database="neo4j") as session:
            return session.read_transaction(self._get_acts_tx, case_id)

    @staticmethod
    def _get_acts_tx(tx, case_id):
        query = (
            "MATCH (c:Case {id: $case_id})-[:REFERS_TO]->(a:Act) "
            "RETURN a.name AS act_name"
        )
        result = tx.run(query, case_id=case_id)
        return [record["act_name"] for record in result]

In [ ]:
# 🚀 Data Ingestion to Neo4j

# --- IMPORTANT ---
# ⚠️ Before running this, clear your database of old, messy data by running this
#    Cypher query in your Neo4j console:
#    MATCH (n) DETACH DELETE n

NEO4J_URI = "neo4j+s://66d16355.databases.neo4j.io"
NEO4J_USER = "neo4j"
NEO4J_PASSWORD = "G4UXZ6KLGd1dzo57rp6ITypJHZ37aM1fn-exAWdw3p8"

print("--- Phase 1: Data Ingestion ---")
neo4j_conn = None
try:
    neo4j_conn = Neo4jConnector(uri=NEO4J_URI, user=NEO4J_USER, password=NEO4J_PASSWORD)
    neo4j_conn.verify_connection()

    print("Pushing clean, standardized data to Neo4j...\n")

    df_to_process = grouped_df
    # display(df_to_process)
    for _, row in df_to_process.iterrows():
        acts = row["standardized_act"] if row["standardized_act"][0] else None
        neo4j_conn.push_case_with_acts(row["case_id"], row["filename"], acts)
        print(f"==> Pushed case '{row['case_id']}' with {len(acts) if acts else 0} acts.")

        # if pd.notna(row.get("filename")):
        #     neo4j_conn.set_case_metadata(row["case_id"], {"filename": row["filename"]})

    print(f"\n✅ Successfully pushed {len(df_to_process)} cases with standardized act relationships to Neo4j.")


except Exception as e:
    print(f"❌ An error occurred during the Neo4j push operation: {e}")

finally:
    if neo4j_conn:
        neo4j_conn.close()
        print("Neo4j push connection closed.")

--- Phase 1: Data Ingestion ---
✅ Connection to Neo4j AuraDB verified successfully.
Pushing clean, standardized data to Neo4j...

==> Pushed case '00d8cbe8-f63a-46cb-b5c9-54b2a837e865' with 0 acts.
==> Pushed case '01678304-fafe-410c-93c4-9eb6b147acaf' with 0 acts.
==> Pushed case '016a8461-93bb-4746-b66c-03ff62926220' with 0 acts.
==> Pushed case '01bf4783-e054-4efc-929e-4feb4700d4f8' with 1 acts.
==> Pushed case '01f89a02-5e35-4d26-ad0e-8bfd4abe138a' with 0 acts.
==> Pushed case '029156bb-e590-44e6-9d47-a6ff2acc578e' with 0 acts.
==> Pushed case '02d57e60-700d-4127-983c-128cd5dcfca4' with 2 acts.
==> Pushed case '02d66939-df82-416a-8808-4a9961f4f67e' with 0 acts.
==> Pushed case '02ed7b72-138a-4cf6-97e5-06b01322fb4c' with 0 acts.
==> Pushed case '037b9a0b-478a-48aa-882d-fa1010e9ff3d' with 0 acts.
==> Pushed case '05d738bb-6b65-4ab6-87dc-9430ac1db158' with 0 acts.
==> Pushed case '064f53c2-43b8-43bf-af14-4677be56b484' with 0 acts.
==> Pushed case '06a98ddb-cf9e-44ee-9437-1307b1f1ab21' with 0 acts.
==> Pushed case '0728263e-0343-4101-908c-9aaaec356ea4' with 0 acts.
==> Pushed case '072a0694-1d0c-4d29-b4c8-fcc7b6dfe9ef' with 1 acts.
==> Pushed case '072d36cd-d3b8-473d-8f1c-008924ee8cbf' with 0 acts.
==> Pushed case '077bec82-91a2-4094-8418-6f93f34842f9' with 0 acts.
==> Pushed case '07ce6884-2cc9-4001-8c00-dc6c3c22f548' with 0 acts.
==> Pushed case '080b4d3d-3b9f-4d7a-90cf-8d457c8e64b9' with 0 acts.
==> Pushed case '082359b1-0049-4a61-a436-51f5583832ac' with 0 acts.
==> Pushed case '084636af-af08-4d22-9b3c-6b9e77be7af2' with 0 acts.
==> Pushed case '086a4c8c-ec9c-4620-8f6c-71c62d9546ec' with 0 acts.
==> Pushed case '088935ba-85e3-4b4a-900b-acce56c85428' with 0 acts.
==> Pushed case '08f48d45-c717-4ac5-8626-3372918d07aa' with 0 acts.
==> Pushed case '0a099e5c-e94a-4230-baac-a8129264a248' with 0 acts.
==> Pushed case '0a481a81-ba1a-49c8-bc56-a9c7b150250d' with 0 acts.
==> Pushed case '0b03db14-7e1c-41d1-b75f-bc930a9702c7' with 0 acts.
==> Pushed case '0b62012f-a1fb-435b-80d5-2a867b52ad09' with 0 acts.
==> Pushed case '0b707d80-6fc3-444f-923c-0b6c0ef4a5ec' with 0 acts.
==> Pushed case '0c195c82-11ab-44d5-b030-f05cbc4425cd' with 0 acts.
==> Pushed case '0d247b2e-fa41-4027-a86c-fd5a46dcd853' with 2 acts.
==> Pushed case '0e292e21-9b0b-4b5e-8cd1-9f10400a1f32' with 0 acts.
==> Pushed case '103b8e60-39a2-4562-aa6b-f12cd44533c0' with 0 acts.
==> Pushed case '11368ee2-af18-4036-93b1-1d53f26536ca' with 0 acts.
==> Pushed case '11a0f7fd-e554-43cf-874d-58d3ccf2ee44' with 0 acts.
==> Pushed case '11dc5496-b9a4-46ff-9b5b-f3fce5f19295' with 2 acts.
==> Pushed case '1225feb1-0f30-46ee-bd1c-5180eeb5c601' with 0 acts.
==> Pushed case '12371d9b-4dac-4c40-9487-4c1f759ad9f8' with 0 acts.
==> Pushed case '125bd30f-b322-4834-98bc-a20cbdb8cfc3' with 1 acts.
==> Pushed case '12605f17-823e-4167-985e-7a833c048751' with 1 acts.
==> Pushed case '12949064-b074-471c-8a17-d5d6bd6597f8' with 0 acts.
==> Pushed case '12c156e8-07d2-42c9-924e-0c1e20a910be' with 3 acts.
==> Pushed case '132c2e7b-1316-4b86-a8a3-db80e3f38f55' with 0 acts.
==> Pushed case '1358d3d2-883f-4651-9501-672f90d35d0c' with 0 acts.
==> Pushed case '135dbf99-6d5d-4d1b-8872-7586404adfd4' with 1 acts.
==> Pushed case '137c849c-00ee-4f17-81bc-77063bb0fc07' with 0 acts.
==> Pushed case '143f0a1a-686b-4cba-88d9-1865cec05e5f' with 0 acts.
==> Pushed case '1462c08b-e99f-441c-a0c8-0082f0d0362b' with 0 acts.
==> Pushed case '15725649-ae6b-46d5-ba95-0fef0770d171' with 0 acts.
==> Pushed case '15ebb8c6-617e-4801-97fa-b79657cac8e0' with 0 acts.
==> Pushed case '1663f88d-0e9a-404a-ac78-37e4e7123bbe' with 1 acts.
==> Pushed case '168f6734-e905-4f14-9a6e-2086580f3b9e' with 2 acts.
==> Pushed case '16ea26dc-6d47-47ee-b14e-57fbe99b399c' with 0 acts.
==> Pushed case '16eace40-ddb1-412c-becb-7cbdbea153bb' with 0 acts.
==> Pushed case '1720d4e1-8623-47b6-8a6d-f744062ba667' with 0 acts.
==> Pushed case '1879977a-a086-41c6-a1e3-5fc4fcf05ab1' with 0 acts.
==> Pushed case '196c1167-6f4c-4b69-ab6f-d80f54c22d5f' with 1 acts.
==> Pushed case '19ffe04a-fc8a-41aa-8ec4-f0ca0266a8f9' with 0 acts.
==> Pushed case '1b0cdfe1-5107-4e70-9d6d-4e965552f7a0' with 0 acts.
==> Pushed case '1b298f2e-eed8-4c5f-9984-13ea788a170a' with 3 acts.
==> Pushed case '1b895da5-766d-4549-9f2c-111b7dd050ee' with 0 acts.
==> Pushed case '1c188f6d-3832-4641-8f4a-a19c747cc0b5' with 0 acts.
==> Pushed case '1d074c60-4c50-437f-8fd4-6bad7e578066' with 1 acts.
==> Pushed case '1e191d25-804a-4089-9fe7-a3db5f355b52' with 0 acts.
==> Pushed case '1e56e882-7e06-4185-9eed-f8d37654308d' with 0 acts.
==> Pushed case '1fd3711c-cee9-4d59-9023-a32cd006f8d1' with 0 acts.
==> Pushed case '20e77e40-0b70-421e-9d39-270a91aa04ba' with 0 acts.
==> Pushed case '22a85995-df8c-44c2-aa15-3fb84f3c0064' with 1 acts.
==> Pushed case '230029f2-0f9c-436c-9b85-7a3093788ab7' with 0 acts.
==> Pushed case '237700f2-6252-40e4-9d16-e1e05ebfbfe5' with 0 acts.
==> Pushed case '239785d6-2cdd-46bc-a88f-80354bf5bb30' with 0 acts.
==> Pushed case '24131d4f-91d2-4b8d-aac5-e0bb7639fee9' with 0 acts.
==> Pushed case '24360ecc-8aa7-4522-b1fc-ec164bc40f67' with 0 acts.
==> Pushed case '24b89c2c-6ad8-477d-ae6c-ca05199bef91' with 0 acts.
==> Pushed case '2584ac4b-9ae7-4eba-8e76-2c04f2c42724' with 0 acts.
==> Pushed case '25ebf165-0d4e-4143-8b1b-ea4c0016b1a5' with 1 acts.
==> Pushed case '26144600-3189-471b-8063-2df3cff41a8c' with 1 acts.

In [ ]:
# ❓ Query a Specific Case and Display Results

def parse_standardized_act_name(act_name_str):
    """Parses a standardized act name back into its components for display."""
    parsing_pattern = re.compile(r'^(.*)\s+No\.\s+(\d+)\s+of\s+(\d{4})$')
    match = parsing_pattern.match(act_name_str)
    if match:
        return {"act_name": match.group(1).strip(), "act_number": match.group(2), "year": match.group(3)}
    return {"act_name": act_name_str, "act_number": "N/A", "year": "N/A"}

# --- CONFIGURATION ---
# <<-- CHANGE THIS ID to the case you want to query from your data
target_case_id = "4c4ebba0-1876-43ba-adf6-79afca98fceb" # Example case ID

print(f"\n--- Phase 2: Querying Data ---")
print(f"\nQuerying for acts referred by Case ID: '{target_case_id}'")

neo4j_conn = None
try:
    neo4j_conn = Neo4jConnector(uri=NEO4J_URI, user=NEO4J_USER, password=NEO4J_PASSWORD)
    neo4j_conn.verify_connection()

    referred_acts = neo4j_conn.get_acts_for_case(target_case_id)

    if referred_acts:
        print(f"Found {len(referred_acts)} referred act(s). Formatting output...")
        formatted_acts = [parse_standardized_act_name(act) for act in referred_acts]

        # Display the results in a clean pandas DataFrame
        acts_df = pd.DataFrame(formatted_acts)
        acts_df = acts_df[["act_name", "act_number", "year"]] # Ensure column order
        display(acts_df)
    else:
        print(f"No referred acts found in the database for Case ID: '{target_case_id}'")

except Exception as e:
    print(f"❌ An error occurred during the Neo4j query operation: {e}")

finally:
    if neo4j_conn:
        neo4j_conn.close()
        print("Neo4j query connection closed.")

--- Phase 2: Querying Data ---

Querying for acts referred by Case ID: '4c4ebba0-1876-43ba-adf6-79afca98fceb'
✅ Connection to Neo4j AuraDB verified successfully.

/tmp/ipython-input-102-3071221803.py:66: DeprecationWarning: read_transaction has been renamed to execute_read
  return session.read_transaction(self._get_acts_tx, case_id)
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: id)} {position: line: 1, column: 16, offset: 15} for query: 'MATCH (c:Case {id: $case_id})-[:REFERS_TO]->(a:Act) RETURN a.name AS act_name'
WARNING:neo4j.notifications:Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: name)} {position: line: 1, column: 62, offset: 61} for query: 'MATCH (c:Case {id: $case_id})-[:REFERS_TO]->(a:Act) RETURN a.name AS act_name'

No referred acts found in the database for Case ID: '4c4ebba0-1876-43ba-adf6-79afca98fceb'
Neo4j query connection closed.